In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8036, 4568, 9959, 4812],
 [8036, 4568, 9959, 338],
 [8036, 9327, 9959, 9209],
 [9808, 5286, 7492, 5632, 9000],
 [9808, 5286, 7492, 5632, 6155],
 [867, 8036, 109, 9959, 4124],
 [6762, 7729, 6775, 5632]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8036 4568 9959 4812]
 [   0    0    0    0 8036 4568 9959  338]
 [   0    0    0    0 8036 9327 9959 9209]
 [   0    0    0 9808 5286 7492 5632 9000]
 [   0    0    0 9808 5286 7492 5632 6155]
 [   0    0    0  867 8036  109 9959 4124]
 [   0    0    0    0 6762 7729 6775 5632]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 354ms/step


array([[[-0.00533428,  0.03901029, -0.03436011,  0.03847798,
          0.00405926,  0.03879669, -0.03933896, -0.03352632,
          0.01320721, -0.03861742],
        [-0.00533428,  0.03901029, -0.03436011,  0.03847798,
          0.00405926,  0.03879669, -0.03933896, -0.03352632,
          0.01320721, -0.03861742],
        [-0.00533428,  0.03901029, -0.03436011,  0.03847798,
          0.00405926,  0.03879669, -0.03933896, -0.03352632,
          0.01320721, -0.03861742],
        [-0.00533428,  0.03901029, -0.03436011,  0.03847798,
          0.00405926,  0.03879669, -0.03933896, -0.03352632,
          0.01320721, -0.03861742],
        [ 0.01763387,  0.00087475,  0.00234804, -0.00828199,
          0.01360461,  0.01380134, -0.03211967, -0.04040321,
          0.02919995, -0.01472484],
        [ 0.01899296,  0.0089888 , -0.03977543,  0.00374008,
         -0.04129763, -0.02610949,  0.04881321, -0.00931878,
          0.00842699,  0.04574622],
        [-0.00672711, -0.0240049 ,  0.0162628 , -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 8036, 4568, 9959, 4812])

In [20]:
x_input = np.expand_dims(embedded_docs[0], axis=0)  # shape (1, sequence_length)
preds = model.predict(x_input)
preds



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


array([[[-0.00533428,  0.03901029, -0.03436011,  0.03847798,
          0.00405926,  0.03879669, -0.03933896, -0.03352632,
          0.01320721, -0.03861742],
        [-0.00533428,  0.03901029, -0.03436011,  0.03847798,
          0.00405926,  0.03879669, -0.03933896, -0.03352632,
          0.01320721, -0.03861742],
        [-0.00533428,  0.03901029, -0.03436011,  0.03847798,
          0.00405926,  0.03879669, -0.03933896, -0.03352632,
          0.01320721, -0.03861742],
        [-0.00533428,  0.03901029, -0.03436011,  0.03847798,
          0.00405926,  0.03879669, -0.03933896, -0.03352632,
          0.01320721, -0.03861742],
        [ 0.01763387,  0.00087475,  0.00234804, -0.00828199,
          0.01360461,  0.01380134, -0.03211967, -0.04040321,
          0.02919995, -0.01472484],
        [ 0.01899296,  0.0089888 , -0.03977543,  0.00374008,
         -0.04129763, -0.02610949,  0.04881321, -0.00931878,
          0.00842699,  0.04574622],
        [-0.00672711, -0.0240049 ,  0.0162628 , -0.0